(ns project-euler.problem2)

(defn calc-fib
  [limit]
  (loop [fib-seq [1 2]]
    (let [next (reduce + (take-last 2 fib-seq))]
      (if (> next limit)
        fib-seq
        (recur (concat fib-seq [next]))))))

(defn problem2
  "https://projecteuler.net/problem=2
  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms."
  []
  (->> (calc-fib 4000000)
       (filter even?)
       (reduce +)))

